### ISSUE TITLE
Fails to build with Python 3.12

### ISSUE THREAD

**Issue by sebastic** [SciTools/cartopy#2301]
### Description

The Debian package failed to build with Python 3.12:
```
aarch64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard -g -fwrapv -O2 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.12 -c lib/cartopy/trace.cpp -o build/temp.linux-aarch64-cpython-312/lib/cartopy/trace.o
lib/cartopy/trace.cpp: In function ‘bool __pyx_f_7cartopy_5trace_degenerate_line(const __pyx_t_7cartopy_5trace_Line&)’:
lib/cartopy/trace.cpp:1623:34: error: ‘_PyCFrame’ {aka ‘struct _PyCFrame’} has no member named ‘use_tracing’
 1623 |      (unlikely((tstate)->cframe->use_tracing) &&\
      |                                  ^~~~~~~~~~~
```
[Full buildlog](https://buildd.debian.org/status/fetch.php?pkg=python-cartopy&arch=arm64&ver=0.22.0%2Bdfsg-1%2Bb1&stamp=1701974552&raw=0)

### Operating system

Debian unstable

### Cartopy version

0.22.0

**Comment by QuLogic** [comment]
The build is fine on Fedora; I think you do need a newer Cython.

**Comment by sebastic** [comment]
Confirmed fixed with cython 3.0.6 from Debian experimental.
